# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 771a2466895e880abeac0be42db1fe3952bc385d92643fd5f9da641a0aa0560ac2fefb691dbb48381e9ab666bfe89970d285e0a470fcd0386c22b8ce62027a37

test:
  secret_key_base: 612681dcd97ba9a2b955be7f098bbab1b9e8b37fc3e614be679618e54e8dc8712fdd40abd2ea8151d29a5cd8c3c1dd86ad6f4601049b4e69b68a2a9d263cd306

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
